name: Deploy .NET 6 WebAPI

on:
  push:
    branches: [ "deploy" ]
  pull_request:
    branches: [ "deploy" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Este bloque verifica y clona el repositorio de la WebAPI si no existe
      - name: Check if repository exists (WebAPI)
        run: |
          if (Test-Path -Path "X:\deploy\lybWepApi_graphQL\Presentation\Presentation.csproj") {
            Write-Output "Repository already exists, pulling changes..."
            cd X:\deploy\lybWepApi_graphQL
            & "C:\Program Files\Git\bin\git.exe" pull origin deploy
          } else {
            Write-Output "Cloning repository..."
            & "C:\Program Files\Git\bin\git.exe" clone https://github.com/YourUsername/YourWebAPIProject.git X:\deploy\lybWepApi_graphQL
          }

      - name: Restore and publish .NET 6 WebAPI
        run: |
          cd X:\deploy\lybWepApi_graphQL\Presentation
          dotnet restore
          dotnet publish -c Release -o ./publish

      # Aquí sigue el resto del flujo para la aplicación Angular sin Node.js ni npm
      - name: Clean public
        run: |
          Get-ChildItem -Path X:\wwwroot\lybApi | Where-Object { $_.Name -notmatch 'web.config',$_.Name -notmatch 'logs' } | ForEach-Object { Remove-Item -Path $_.FullName -Recurse -Force }

      - name: Copy Files dist to public
        run: |
          Copy-Item -Path "X:\deploy\lybWepApi_graphQL\Presentation\publish*" -Destination "X:\wwwroot\lybApi" -Recurse -Force
